sudo: required
services:
  - docker

before_install: 
  - docker build -t hervs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hervs/react-test npm test 

after_success:
  - docker build -t hervs/multi-client ./client
  - docker build -t hervs/multi-nginx ./nginx
  - docker build -t hervs/multi-server ./server
  - docker build -t hervs/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hervs/multi-client
  - docker push hervs/multi-nginx 
  - docker push hervs/multi-server
  - docker push hervs/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-844476188546
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
